version: '3'

services:
  home:
    build:
      context: .
    ports:
    - "80:80"

  bezie:
    build: 'bezie'
    ports:
    - "3000:80"
  newsify:
    build: 'newsify'
    ports:
    - "3001:80"
  twitter:
    build: 'twitter-project'
    ports:
    - "3002:80"
