version: "3"

services:
  home:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  home-page:
    image: ghcr.io/montecamo/home-page:master
    container_name: home-page

  newsify:
    image: ghcr.io/montecamo/newsify:master
    container_name: newsify

  bezie:
    image: ghcr.io/montecamo/bezie:master
    container_name: bezie

  fracty:
    image: ghcr.io/montecamo/fracty:master
    container_name: fracty

  pixiwave:
    image: ghcr.io/montecamo/pixiwave:master
    container_name: pixiwave

  jobos:
    image: ghcr.io/montecamo/jobos:master
    container_name: jobos

  twitter:
    image: registry.gitlab.com/montecamo/twitter-project:latest
    container_name: twitter

  daves:
    image: registry.gitlab.com/montecamo/daves:latest
    container_name: daves

  pushed:
    image: ghcr.io/montecamo/pushed:master
    container_name: pushed

  resplash-api:
    image: ghcr.io/montecamo/resplash-api:master
    container_name: resplash-api

  resplash:
    image: ghcr.io/montecamo/resplash:master
    container_name: resplash

  moovie:
    image: ghcr.io/montecamo/mooviego:master
    container_name: moovie

  moovie-bot:
    image: ghcr.io/montecamo/mooviego-bot:master
    container_name: moovie-bot

  cors-proxy:
    image: ghcr.io/theboringindustries/cors-anywhere:master
    container_name: "cors-proxy"
    ports:
      - "8443:443"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    container_name: "mongo"
    volumes: ["~/mongo/data:/data/db"]

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
