version: '3'

services:
  home:
    build:
      context: .
    ports:
    - "80:80"
    - "443:443"
    - "8443:8443"
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  bezie:
    build: 'projects/bezie'
    container_name: 'bezie'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  newsify:
    build: 'projects/newsify'
    container_name: 'newsify'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  twitter:
    build: 'projects/twitter-project'
    container_name: 'twitter'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  fracty:
    build: 'projects/fracty'
    container_name: 'fracty'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  pixiwave:
    build: 'projects/pixiwave'
    container_name: 'pixiwave'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  jobos:
    build: 'projects/jobos'
    container_name: 'jobos'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  daves:
    build: 'projects/daves'
    container_name: 'daves'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt

  pushed:
    build: 'projects/pushed'
    container_name: 'pushed'
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt