---
- name: Create New User
  hosts: all
  gather_facts: false
  become: yes
  vars_files:
    - vars/secret.yml
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        groups:
        - sudo
        - docker
        append: yes

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"